name: Java CI with Maven and JUnit

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'

      -name: Build with Maven
        run: mvn clean package

      -name: Run JUnit Tests and generate reports
        run: mvn test surefire-reports:report
        continue-on-error: true

      -name: List files in target directory
        run: ls -R target

      -name: List files in surefire-reports directory
        run: ls -R target/surefire-reports

      -name: Upload JUnit Test reports
        uses: actions/upload-artifact@v2
        with:
          name: junit-reports
          path: target/surefire-reports0

