
name: Java CI with Maven and Junit test

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2 

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11' 
          distribution: 'adopt' 
 

      - name: Build with Maven
        run: mvn -B package --file pom.xml  

      - name: Run JUnit tests and generate reports
        run: mvn test surefire-report:report 
        continue-on-error: true

      - name: Upload Junit test reports
        uses: actions/upload-artifacts@v2
        with:
          name: junit-reports
          path: target/surefire-reports

      - name: Display Junit test reports
        if: always()
        run:
          echo "Junit Test reports:"
          cat target/surefire-reports/*.txt